# **Time Series Analysis of Housing Market in Ames, Iowa**

## **Introduction :**

Over the past few years, housing has changed a lot. Rising incomes, higher living costs, and homeowners wanting better upgrades have reshaped how houses are built and designed. Even rural areas have seen sharp price increases.

Usually when somebody considering to buy house consider the neighborhood, type of house, attributes of the house, type of sale, and time are factored into the price. We will try to understand these factors and  how they have affected the price of houses over time to see the change that was explained above.

The data was collected by De Cock where 81 dimensions were recorded for 1460 properties in Ames IA.

Brief description of columns:

**1. Identification**
- **Id:** Property ID (unique identifier).

__2. Sale Information__
- **SalePrice:** Target variable — final selling price.
- **SaleType:** Type of sale (e.g., Warranty Deed).
- **SaleCondition:** Condition of sale (Normal, Abnormal, Partial).

__3. Lot & Land__
- **MSSubClass:** Dwelling type (e.g., 1-story, 2-story).
- **MSZoning:** Zoning classification.
- **LotFrontage:** Street frontage length.
- **LotArea:** Lot size (sq ft).
- **Street:** Road access type.
- **Alley:** Alley access type.
- **LotShape:** Lot shape (Regular, Irregular).
- **LandContour:** Flatness of property.
- **Utilities:** Available utilities.
- **LotConfig:** Lot configuration (Corner, Inside).
- **LandSlope:** Slope of property.
- **Neighborhood:** Physical location within Ames.
- **Condition1/Condition2:** Proximity to roads, railways, etc.

__4. Building & Construction__

- **BldgType:** Building type (Single-family, Duplex).
- **HouseStyle:** House style (1-story, 2-story, split-level).
- **OverallQual:** Overall material/finish quality (1–10).
- **OverallCond:** Overall condition (1–10).
- **YearBuilt:** Year built.
- **YearRemodAdd:** Remodel year.
- **RoofStyle:** Roof type.
- **RoofMatl:** Roof material.
- **Exterior1st/Exterior2nd:** Exterior covering materials.
- **MasVnrType:** Masonry veneer type.
- **MasVnrArea:** Masonry veneer area (sq ft).
- **ExterQual:** Exterior quality.
- **ExterCond:** Exterior condition.

__5. Interior Features__

- **Foundation:** Foundation type.
- **BsmtQual:** Basement quality.
- **BsmtCond:** Basement condition.
- **BsmtExposure:** Basement exposure (walkout, garden).
- **BsmtFinType1/BsmtFinType2:** Basement finish types.
- **BsmtFinSF1/BsmtFinSF2:** Finished basement area (sq ft).
- **BsmtUnfSF:** Unfinished basement area.
- **TotalBsmtSF:** Total basement area.
- **Heating:** Heating type.
- **HeatingQC:** Heating quality.
- **CentralAir:** Central air (Y/N).
- **Electrical:** Electrical system.
- **1stFlrSF:** First floor area.
- **2ndFlrSF:** Second floor area.
- **LowQualFinSF:** Low-quality finished area.
- **GrLivArea:** Above-ground living area.
- **BsmtFullBath/BsmtHalfBath:** Basement bathrooms.
- **FullBath/HalfBath:** Bathrooms above ground.
- **BedroomAbvGr:** Bedrooms above ground.
- **KitchenAbvGr:** Kitchens above ground.
- **KitchenQual:** Kitchen quality.
- **TotRmsAbvGrd:** Total rooms above ground.
- **Functional:** Home functionality rating.
- **Fireplaces:** Number of fireplaces.
- **FireplaceQu:** Fireplace quality.

__6. Garage__
- **GarageType:** Garage location.
- **GarageYrBlt:** Year garage built.
- **GarageFinish:** Garage finish.
- **GarageCars:** Garage capacity (cars).
- **GarageArea:** Garage area (sq ft).
- **GarageQual:** Garage quality.
- **GarageCond:** Garage condition.

**7.Outdoor & Misc**

- **PavedDrive:** Paved driveway (Y/N).
- **WoodDeckSF:** Wood deck area (sq ft).
- **OpenPorchSF:** Open porch area.
- **EnclosedPorch:** Enclosed porch area.
- **3SsnPorch:** Three-season porch area.
- **ScreenPorch:** Screen porch area.
- **PoolArea:** Pool area (sq ft).
- **PoolQC:** Pool quality.
- **Fence:** Fence quality.
- **MiscFeature:** Miscellaneous features (shed, tennis court).
- **MiscVal:** Value of miscellaneous features.

__8. Living Space Totals__
- **MoSold:** Month sold.
- **YrSold:** Year sold.

**This dataset represents the sale of  residential properties in Ames, Iowa, where every single record represents a sale of individual house.
There are identification, location, land lot information, house characteristics, exterior, interior, garge, sales information and other features describing each house. The data spans from 2006 to 2010.**

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
%matplotlib inline
import matplotlib.pyplot as plt
from scipy import stats
from pathlib import Path
import sidetable
from sklearn.preprocessing import StandardScaler
from sklearn.manifold import MDS
import statsmodels.api as sm

In [2]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
import warnings
warnings.filterwarnings("ignore")
# set the decimal places to 2
pd.set_option("display.float_format", "{:.2f}".format)

In [3]:
path = Path.cwd().parent
data_path = path.joinpath("data", "raw")
files = []
for file in data_path.rglob("*.csv"):
    files.append(file)
    print(file.name)
    print(files.index(file), " ", file)

sample_submission.csv
0   e:\house_price_prediction\Real-Estate-Price-Prediction\data\raw\extracted\sample_submission.csv
test.csv
1   e:\house_price_prediction\Real-Estate-Price-Prediction\data\raw\extracted\test.csv
train.csv
2   e:\house_price_prediction\Real-Estate-Price-Prediction\data\raw\extracted\train.csv

In [4]:
# Read train and test
df_train = pd.read_csv(files[2])
df_test = pd.read_csv(files[1])
print("Training Dataset:")
display(df_train.head(1))
print("\n")
print("Testing Dataset:")
display(df_test.head(1))

Training Dataset:

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.00,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.00,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.00,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500

Testing Dataset:

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.00,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Feedr,Norm,1Fam,1Story,5,6,1961,1961,Gable,CompShg,VinylSd,VinylSd,NaN,0.00,TA,TA,CBlock,TA,TA,No,Rec,468.00,LwQ,144.00,270.00,882.00,GasA,TA,Y,SBrkr,896,0,0,896,0.00,0.00,1,0,2,1,TA,5,Typ,0,NaN,Attchd,1961.00,Unf,1.00,730.00,TA,TA,Y,140,0,0,0,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal

In [5]:
# Basic info of datasets
print(f"Training Dataset Shape : {df_train.shape}")
print(f"Testing Dataset Shape : {df_test.shape}")

Training Dataset Shape : (1460, 81)
Testing Dataset Shape : (1459, 80)

In [6]:
# remove whitespace from columns name, replace space to '_' for columns name for conveince

df_train.columns = df_train.columns.str.strip().str.replace(" ", "_").str.replace(".", "_")#.str.lower()
df_test.columns = df_test.columns.str.strip().str.replace(" ", "_").str.replace(".", "_")

In [7]:
dtype_df = pd.DataFrame(index=df_train.columns, columns=['Dtype','nunique','unique'])
dtype_df['Dtype'] = df_train.dtypes
dtype_df['nunique'] = df_train.nunique()
dtype_df['unique'] = [df_train[col].unique() for col in df_train.columns]
dtype_df

,Dtype,nunique,unique
Id,int64,1460,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14..."
MSSubClass,int64,15,"[60, 20, 70, 50, 190, 45, 90, 120, 30, 85, 80,..."
MSZoning,object,5,"[RL, RM, C (all), FV, RH]"
LotFrontage,float64,110,"[65.0, 80.0, 68.0, 60.0, 84.0, 85.0, 75.0, nan..."
LotArea,int64,1073,"[8450, 9600, 11250, 9550, 14260, 14115, 10084,..."
Street,object,2,"[Pave, Grvl]"
Alley,object,2,"[nan, Grvl, Pave]"
LotShape,object,4,"[Reg, IR1, IR2, IR3]"
LandContour,object,4,"[Lvl, Bnk, Low, HLS]"
Utilities,object,2,"[AllPub, NoSeWa]"
LotConfig,object,5,"[Inside, FR2, Corner, CulDSac, FR3]"
LandSlope,object,3,"[Gtl, Mod, Sev]"
Neighborhood,object,25,"[CollgCr, Veenker, Crawfor, NoRidge, Mitchel, ..."
Condition1,object,9,"[Norm, Feedr, PosN, Artery, RRAe, RRNn, RRAn, ..."
Condition2,object,8,"[Norm, Artery, RRNn, Feedr, PosN, PosA, RRAn, ..."
BldgType,object,5,"[1Fam, 2fmCon, Duplex, TwnhsE, Twnhs]"
HouseStyle,object,8,"[2Story, 1Story, 1.5Fin, 1.5Unf, SFoyer, SLvl,..."
OverallQual,int64,10,"[7, 6, 8, 5, 9, 4, 10, 3, 1, 2]"
OverallCond,int64,9,"[5, 8, 6, 7, 4, 2, 3, 9, 1]"
YearBuilt,int64,112,"[2003, 1976, 2001, 1915, 2000, 1993, 2004, 197..."
YearRemodAdd,int64,61,"[2003, 1976, 2002, 1970, 2000, 1995, 2005, 197..."
RoofStyle,object,6,"[Gable, Hip, Gambrel, Mansard, Flat, Shed]"
RoofMatl,object,8,"[CompShg, WdShngl, Metal, WdShake, Membran, Ta..."
Exterior1st,object,15,"[VinylSd, MetalSd, Wd Sdng, HdBoard, BrkFace, ..."
Exterior2nd,object,16,"[VinylSd, MetalSd, Wd Shng, HdBoard, Plywood, ..."
MasVnrType,object,3,"[BrkFace, nan, Stone, BrkCmn]"
MasVnrArea,float64,327,"[196.0, 0.0, 162.0, 350.0, 186.0, 240.0, 286.0..."
ExterQual,object,4,"[Gd, TA, Ex, Fa]"
ExterCond,object,5,"[TA, Gd, Fa, Po, Ex]"
Foundation,object,6,"[PConc, CBlock, BrkTil, Wood, Slab, Stone]"
BsmtQual,object,4,"[Gd, TA, Ex, nan, Fa]"
BsmtCond,object,4,"[TA, Gd, nan, Fa, Po]"
BsmtExposure,object,4,"[No, Gd, Mn, Av, nan]"
BsmtFinType1,object,6,"[GLQ, ALQ, Unf, Rec, BLQ, nan, LwQ]"
BsmtFinSF1,int64,637,"[706, 978, 486, 216, 655, 732, 1369, 859, 0, 8..."
BsmtFinType2,object,6,"[Unf, BLQ, nan, ALQ, Rec, LwQ, GLQ]"
BsmtFinSF2,int64,144,"[0, 32, 668, 486, 93, 491, 506, 712, 362, 41, ..."
BsmtUnfSF,int64,780,"[150, 284, 434, 540, 490, 64, 317, 216, 952, 1..."
TotalBsmtSF,int64,721,"[856, 1262, 920, 756, 1145, 796, 1686, 1107, 9..."
Heating,object,6,"[GasA, GasW, Grav, Wall, OthW, Floor]"
HeatingQC,object,5,"[Ex, Gd, TA, Fa, Po]"
CentralAir,object,2,"[Y, N]"
Electrical,object,5,"[SBrkr, FuseF, FuseA, FuseP, Mix, nan]"
1stFlrSF,int64,753,"[856, 1262, 920, 961, 1145, 796, 1694, 1107, 1..."
2ndFlrSF,int64,417,"[854, 0, 866, 756, 1053, 566, 983, 752, 1142, ..."
LowQualFinSF,int64,24,"[0, 360, 513, 234, 528, 572, 144, 392, 371, 39..."
GrLivArea,int64,861,"[1710, 1262, 1786, 1717, 2198, 1362, 1694, 209..."
BsmtFullBath,int64,4,"[1, 0, 2, 3]"
BsmtHalfBath,int64,3,"[0, 1, 2]"
FullBath,int64,4,"[2, 1, 3, 0]"
HalfBath,int64,3,"[1, 0, 2]"
BedroomAbvGr,int64,8,"[3, 4, 1, 2, 0, 5, 6, 8]"
KitchenAbvGr,int64,4,"[1, 2, 3, 0]"
KitchenQual,object,4,"[Gd, TA, Ex, Fa]"
TotRmsAbvGrd,int64,12,"[8, 6, 7, 9, 5, 11, 4, 10, 12, 3, 2, 14]"
Functional,object,7,"[Typ, Min1, Maj1, Min2, Mod, Maj2, Sev]"
Fireplaces,int64,4,"[0, 1, 2, 3]"
FireplaceQu,object,5,"[nan, TA, Gd, Fa, Ex, Po]"
GarageType,object,6,"[Attchd, Detchd, BuiltIn, CarPort, nan, Basmen..."
GarageYrBlt,float64,97,"[2003.0, 1976.0, 2001.0, 1998.0, 2000.0, 1993...."
GarageFinish,object,3,"[RFn, Unf, Fin, nan]"
GarageCars,int64,5,"[2, 3, 1, 0, 4]"
GarageArea,int64,441,"[548, 460, 608, 642, 836, 480, 636, 484, 468, ..."
GarageQual,object,5,"[TA, Fa, Gd, nan, Ex, Po]"
GarageCond,object,5,"[TA, Fa, nan, Gd, Po, Ex]"
PavedDrive,object,3,"[Y, N, P]"
WoodDeckSF,int64,274,"[0, 298, 192, 40, 255, 235, 90, 147, 140, 160,..."
OpenPorchSF,int64,202,"[61, 0, 42, 35, 84, 30, 57, 204, 4, 21, 33, 21..."
EnclosedPorch,int64,120,"[0, 272, 228, 205, 176, 87, 172, 102, 37, 144,..."
3SsnPorch,int64,20,"[0, 320, 407, 130, 180, 168, 140, 508, 238, 24..."
ScreenPorch,int64,76,"[0, 176, 198, 291, 252, 99, 184, 168, 130, 142..."
PoolArea,int64,8,"[0, 512, 648, 576, 555, 480, 519, 738]"
PoolQC,object,3,"[nan, Ex, Fa, Gd]"
Fence,object,4,"[nan, MnPrv, GdWo, GdPrv, MnWw]"
MiscFeature,object,4,"[nan, Shed, Gar2, Othr, TenC]"
MiscVal,int64,21,"[0, 700, 350, 500, 400, 480, 450, 15500, 1200,..."
MoSold,int64,12,"[2, 5, 9, 12, 10, 8, 11, 4, 1, 7, 3, 6]"
YrSold,int64,5,"[2008, 2007, 2006, 2009, 2010]"
SaleType,object,9,"[WD, New, COD, ConLD, ConLI, CWD, ConLw, Con, ..."
SaleCondition,object,6,"[Normal, Abnorml, Partial, AdjLand, Alloca, Fa..."
SalePrice,int64,663,"[208500, 181500, 223500, 140000, 250000, 14300..."

### **Time Series Analysis with Graphs**